FROM python:3.10-slim
LABEL env="production"

WORKDIR /app
COPY src_code/ /app/

RUN pip install --no-cache-dir flask flask-cors gunicorn

EXPOSE 5000
CMD ["gunicorn", "--workers=4", "--worker-class=gevent", "--bind=0.0.0.0:5000", "app:app"]
